# Generated by Django 4.0.2 on 2022-04-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_location_active_location_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='name',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='name',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
